// Generated by scripts/update_version - do not edit
#ifndef DUST_RANDOM_VERSION_HPP
#define DUST_RANDOM_VERSION_HPP

#define DUST_VERSION_MAJOR 0
#define DUST_VERSION_MINOR 11
#define DUST_VERSION_PATCH 23
#define DUST_VERSION_STRING "0.11.23"
#define DUST_VERSION_CODE 1123

#endif
