// Generated by scripts/update_ziggurat_tables - do not edit
#ifndef DUST_RANDOM_NORMAL_ZIGGURAT_TABLES_HPP
#define DUST_RANDOM_NORMAL_ZIGGURAT_TABLES_HPP

#include "dust/random/cuda_compatibility.hpp"

#ifndef DUST_ZIGGURAT_REAL_TYPE
#define DUST_ZIGGURAT_REAL_TYPE double
#endif

namespace dust {
namespace random {
namespace ziggurat {

CONSTANT
DUST_ZIGGURAT_REAL_TYPE x[257] = {
{{x}}
};

CONSTANT
DUST_ZIGGURAT_REAL_TYPE y[256] = {
{{y}}
};

}
}
}

#endif
