// Generated by scripts/update_ziggurat_tables - do not edit
#ifndef DUST_RANDOM_NORMAL_ZIGGURAT_TABLES_HPP
#define DUST_RANDOM_NORMAL_ZIGGURAT_TABLES_HPP

namespace dust {
namespace random {
namespace ziggurat {

CONSTANT
double x[257] = {
{{x}}
};

CONSTANT
double y[256] = {
{{y}}
};

}
}
}

#endif
