language: r
cache: packages
dist: xenial
addons:
  apt:
    packages:
      - libnode-dev
r_packages:
  - covr
r_github_packages:
  - r-lib/cpp11
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
