// Generated by cpp11: do not edit by hand


#include "cpp11/declarations.hpp"

// dust.hpp
SEXP dust_volatilitygpu_alloc(cpp11::list r_data, size_t step, size_t n_particles, size_t n_threads, size_t seed);
extern "C" SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_alloc(SEXP r_data, SEXP step, SEXP n_particles, SEXP n_threads, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_volatilitygpu_alloc(cpp11::unmove(cpp11::as_cpp<cpp11::list>(r_data)), cpp11::unmove(cpp11::as_cpp<size_t>(step)), cpp11::unmove(cpp11::as_cpp<size_t>(n_particles)), cpp11::unmove(cpp11::as_cpp<size_t>(n_threads)), cpp11::unmove(cpp11::as_cpp<size_t>(seed))));
  END_CPP11
}
// dust.hpp
SEXP dust_volatilitygpu_run(SEXP ptr, size_t step_end);
extern "C" SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_run(SEXP ptr, SEXP step_end) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_volatilitygpu_run(cpp11::unmove(cpp11::as_cpp<SEXP>(ptr)), cpp11::unmove(cpp11::as_cpp<size_t>(step_end))));
  END_CPP11
}
// dust.hpp
SEXP dust_volatilitygpu_set_index(SEXP ptr, cpp11::sexp r_index);
extern "C" SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_set_index(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_volatilitygpu_set_index(cpp11::unmove(cpp11::as_cpp<SEXP>(ptr)), cpp11::unmove(cpp11::as_cpp<cpp11::sexp>(r_index))));
  END_CPP11
}
// dust.hpp
SEXP dust_volatilitygpu_set_state(SEXP ptr, SEXP r_state, SEXP r_step);
extern "C" SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_set_state(SEXP ptr, SEXP r_state, SEXP r_step) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_volatilitygpu_set_state(cpp11::unmove(cpp11::as_cpp<SEXP>(ptr)), cpp11::unmove(cpp11::as_cpp<SEXP>(r_state)), cpp11::unmove(cpp11::as_cpp<SEXP>(r_step))));
  END_CPP11
}
// dust.hpp
SEXP dust_volatilitygpu_reset(SEXP ptr, cpp11::list r_data, size_t step);
extern "C" SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_reset(SEXP ptr, SEXP r_data, SEXP step) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_volatilitygpu_reset(cpp11::unmove(cpp11::as_cpp<SEXP>(ptr)), cpp11::unmove(cpp11::as_cpp<cpp11::list>(r_data)), cpp11::unmove(cpp11::as_cpp<size_t>(step))));
  END_CPP11
}
// dust.hpp
SEXP dust_volatilitygpu_state(SEXP ptr, SEXP r_index);
extern "C" SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_state(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_volatilitygpu_state(cpp11::unmove(cpp11::as_cpp<SEXP>(ptr)), cpp11::unmove(cpp11::as_cpp<SEXP>(r_index))));
  END_CPP11
}
// dust.hpp
size_t dust_volatilitygpu_step(SEXP ptr);
extern "C" SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_step(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust_volatilitygpu_step(cpp11::unmove(cpp11::as_cpp<SEXP>(ptr))));
  END_CPP11
}
// dust.hpp
void dust_volatilitygpu_reorder(SEXP ptr, cpp11::sexp r_index);
extern "C" SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    dust_volatilitygpu_reorder(cpp11::unmove(cpp11::as_cpp<SEXP>(ptr)), cpp11::unmove(cpp11::as_cpp<cpp11::sexp>(r_index)));
    return R_NilValue;
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_alloc(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_reorder(SEXP, SEXP);
extern SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_reset(SEXP, SEXP, SEXP);
extern SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_run(SEXP, SEXP);
extern SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_set_index(SEXP, SEXP);
extern SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_set_state(SEXP, SEXP, SEXP);
extern SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_state(SEXP, SEXP);
extern SEXP _volatilitygpu5f8227e8_dust_volatilitygpu_step(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_volatilitygpu5f8227e8_dust_volatilitygpu_alloc",     (DL_FUNC) &_volatilitygpu5f8227e8_dust_volatilitygpu_alloc,     5},
    {"_volatilitygpu5f8227e8_dust_volatilitygpu_reorder",   (DL_FUNC) &_volatilitygpu5f8227e8_dust_volatilitygpu_reorder,   2},
    {"_volatilitygpu5f8227e8_dust_volatilitygpu_reset",     (DL_FUNC) &_volatilitygpu5f8227e8_dust_volatilitygpu_reset,     3},
    {"_volatilitygpu5f8227e8_dust_volatilitygpu_run",       (DL_FUNC) &_volatilitygpu5f8227e8_dust_volatilitygpu_run,       2},
    {"_volatilitygpu5f8227e8_dust_volatilitygpu_set_index", (DL_FUNC) &_volatilitygpu5f8227e8_dust_volatilitygpu_set_index, 2},
    {"_volatilitygpu5f8227e8_dust_volatilitygpu_set_state", (DL_FUNC) &_volatilitygpu5f8227e8_dust_volatilitygpu_set_state, 3},
    {"_volatilitygpu5f8227e8_dust_volatilitygpu_state",     (DL_FUNC) &_volatilitygpu5f8227e8_dust_volatilitygpu_state,     2},
    {"_volatilitygpu5f8227e8_dust_volatilitygpu_step",      (DL_FUNC) &_volatilitygpu5f8227e8_dust_volatilitygpu_step,      1},
    {NULL, NULL, 0}
};
}

extern "C" void R_init_volatilitygpu5f8227e8(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
