context("package")

test_that("validate package", {
  skip_if_not_installed("pkgload")

  path <- create_test_package()
  ## ensure we create these as needed
  file.remove(file.path(path, "R"))
  file.remove(file.path(path, "src"))

  path <- dust_package(path)

  pkgbuild::compile_dll(path, quiet = TRUE)
  res <- pkgload::load_all(path)
  w <- res$env$walk$new(list(sd = 1), 0, 100)
  expect_equal(w$state(), matrix(0, 1, 100))
  rm(w)
  gc()
  pkgload::unload("pkg")
})


test_that("validate package dependencies", {
  deps <- data.frame(
    type = c("LinkingTo", "LinkingTo", "Imports"),
    package = c("Rcpp", "dust", "Rcpp"),
    version = "*",
    stringsAsFactors = FALSE)
  expect_silent(package_validate_has_dep(deps, "Rcpp", "LinkingTo"))
  expect_silent(package_validate_has_dep(deps, "Rcpp", "Imports"))
  expect_error(
    package_validate_has_dep(deps, "Rcpp", "Depends"),
    "Expected package 'Rcpp' as 'Depends' in DESCRIPTION")
  expect_error(
    package_validate_has_dep(deps, "other", "Imports"),
    "Expected package 'other' as 'Imports' in DESCRIPTION")
})


test_that("validate destination notices existing C++ code", {
  msg <- "File '.+\\.cpp' does not look like it was created by dust - stopping"
  path <- create_test_package()

  path_cpp <- file.path(path, "src", "walk.cpp")
  file.create(path_cpp)

  expect_error(
    package_validate_destination(path, c("sir.cpp", "walk.cpp")),
    msg)

  writeLines("// some actual content", path_cpp)
  expect_error(
    package_validate_destination(path, c("sir.cpp", "walk.cpp")),
    msg)

  writeLines("// Generated by dust", path_cpp)
  expect_silent(
    package_validate_destination(path, c("sir.cpp", "walk.cpp")))
})


test_that("validate destination notices existing R code", {
  msg <- "File '.+\\.R' does not look like it was created by dust - stopping"
  path <- create_test_package()

  path_r <- file.path(path, "R", "dust.R")
  file.create(path_r)

  expect_error(
    package_validate_destination(path, character()),
    msg)

  writeLines("## some actual content", path_r)
  expect_error(
    package_validate_destination(path, character()),
    msg)

  writeLines("## Generated by dust", path_r)
  expect_silent(
    package_validate_destination(path, character()))
})


test_that("Fail to run if no dust files found", {
  path <- create_test_package()
  unlink(dir(file.path(path, "inst", "dust"), full.names = TRUE))
  expect_error(
    dust_package(path),
    "No dust files found in '.+/inst/dust'")
})


test_that("Fail to run if NAMESPACE missing", {
  path <- create_test_package()
  unlink(file.path(path, "NAMESPACE"))
  expect_error(
    package_validate(path),
    "Expected a file 'NAMESPACE' at path '.+'")
})


test_that("Fail to run if DESCRIPTION missing", {
  path <- create_test_package()
  unlink(file.path(path, "DESCRIPTION"))
  expect_error(
    package_validate(path),
    "Expected a file 'DESCRIPTION' at path '.+'")
})
