#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

# In case we switch agents between steps
[ ! -z $(docker images -q $TAG_SHA) ] || docker pull $TAG_SHA

DUST_BASE="$TAG_SHA"
DUST_CUDA="${PACKAGE_ORG}/${PACKAGE_NAME}-cuda:${GIT_SHA}"

docker build \
       --build-arg DUST_BASE=$DUST_BASE \
       --tag $DUST_CUDA \
       -f $PACKAGE_ROOT/docker/Dockerfile.cuda \
       $PACKAGE_ROOT

docker run -it --rm -v $PWD:/src:ro $DUST_CUDA /compile_gpu_model
