# Generated by cpp11: do not edit by hand

dust_volatilitygpu_alloc <- function(r_data, step, n_particles, n_threads, seed) {
  .Call("_volatilitygpu5f8227e8_dust_volatilitygpu_alloc", r_data, step, n_particles, n_threads, seed)
}

dust_volatilitygpu_run <- function(ptr, step_end) {
  .Call("_volatilitygpu5f8227e8_dust_volatilitygpu_run", ptr, step_end)
}

dust_volatilitygpu_set_index <- function(ptr, r_index) {
  .Call("_volatilitygpu5f8227e8_dust_volatilitygpu_set_index", ptr, r_index)
}

dust_volatilitygpu_set_state <- function(ptr, r_state, r_step) {
  .Call("_volatilitygpu5f8227e8_dust_volatilitygpu_set_state", ptr, r_state, r_step)
}

dust_volatilitygpu_reset <- function(ptr, r_data, step) {
  .Call("_volatilitygpu5f8227e8_dust_volatilitygpu_reset", ptr, r_data, step)
}

dust_volatilitygpu_state <- function(ptr, r_index) {
  .Call("_volatilitygpu5f8227e8_dust_volatilitygpu_state", ptr, r_index)
}

dust_volatilitygpu_step <- function(ptr) {
  .Call("_volatilitygpu5f8227e8_dust_volatilitygpu_step", ptr)
}

dust_volatilitygpu_reorder <- function(ptr, r_index) {
  invisible(.Call("_volatilitygpu5f8227e8_dust_volatilitygpu_reorder", ptr, r_index))
}
