# Generated by cpp11: do not edit by hand

dust_sirs_alloc <- function(r_data, step, n_particles, n_threads, seed) {
  .Call("_gpupkg_dust_sirs_alloc", r_data, step, n_particles, n_threads, seed)
}

dust_sirs_run <- function(ptr, step_end) {
  .Call("_gpupkg_dust_sirs_run", ptr, step_end)
}

dust_sirs_set_index <- function(ptr, r_index) {
  .Call("_gpupkg_dust_sirs_set_index", ptr, r_index)
}

dust_sirs_set_state <- function(ptr, r_state, r_step) {
  .Call("_gpupkg_dust_sirs_set_state", ptr, r_state, r_step)
}

dust_sirs_reset <- function(ptr, r_data, step) {
  .Call("_gpupkg_dust_sirs_reset", ptr, r_data, step)
}

dust_sirs_state <- function(ptr, r_index) {
  .Call("_gpupkg_dust_sirs_state", ptr, r_index)
}

dust_sirs_step <- function(ptr) {
  .Call("_gpupkg_dust_sirs_step", ptr)
}

dust_sirs_reorder <- function(ptr, r_index) {
  invisible(.Call("_gpupkg_dust_sirs_reorder", ptr, r_index))
}

dust_volatility_alloc <- function(r_data, step, n_particles, n_threads, seed) {
  .Call("_gpupkg_dust_volatility_alloc", r_data, step, n_particles, n_threads, seed)
}

dust_volatility_run <- function(ptr, step_end) {
  .Call("_gpupkg_dust_volatility_run", ptr, step_end)
}

dust_volatility_set_index <- function(ptr, r_index) {
  .Call("_gpupkg_dust_volatility_set_index", ptr, r_index)
}

dust_volatility_set_state <- function(ptr, r_state, r_step) {
  .Call("_gpupkg_dust_volatility_set_state", ptr, r_state, r_step)
}

dust_volatility_reset <- function(ptr, r_data, step) {
  .Call("_gpupkg_dust_volatility_reset", ptr, r_data, step)
}

dust_volatility_state <- function(ptr, r_index) {
  .Call("_gpupkg_dust_volatility_state", ptr, r_index)
}

dust_volatility_step <- function(ptr) {
  .Call("_gpupkg_dust_volatility_step", ptr)
}

dust_volatility_reorder <- function(ptr, r_index) {
  invisible(.Call("_gpupkg_dust_volatility_reorder", ptr, r_index))
}
