## Generated by dust (version 0.4.1) - do not edit
sirs <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    data = NULL,
    ptr = NULL
  ),

  public = list(
    initialize = function(data, step, n_particles, n_threads = 1L,
                          seed = 1L) {
      res <- dust_sirs_alloc(data, step, n_particles,
                        n_threads, seed)
      private$ptr <- res[[1L]]
      private$data <- res[[2L]]
    },

    name = function() {
      "sirs"
    },

    run = function(step_end) {
      dust_sirs_run(private$ptr, step_end)
    },

    set_index = function(index) {
      dust_sirs_set_index(private$ptr, index)
    },

    set_state = function(state, step = NULL) {
      dust_sirs_set_state(private$ptr, state, step)
    },

    reset = function(data, step) {
      private$data <- dust_sirs_reset(private$ptr, data, step)
      invisible()
    },

    state = function(index = NULL) {
      dust_sirs_state(private$ptr, index)
    },

    step = function() {
      dust_sirs_step(private$ptr)
    },

    reorder = function(index) {
      dust_sirs_reorder(private$ptr, as.integer(index))
      invisible()
    },

    info = function() {
      private$data
    },

    rng_state = function() {
      dust_sirs_rng_state(private$ptr)
    }
  ))
volatility <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    data = NULL,
    ptr = NULL
  ),

  public = list(
    initialize = function(data, step, n_particles, n_threads = 1L,
                          seed = 1L) {
      res <- dust_volatility_alloc(data, step, n_particles,
                        n_threads, seed)
      private$ptr <- res[[1L]]
      private$data <- res[[2L]]
    },

    name = function() {
      "volatility"
    },

    run = function(step_end) {
      dust_volatility_run(private$ptr, step_end)
    },

    set_index = function(index) {
      dust_volatility_set_index(private$ptr, index)
    },

    set_state = function(state, step = NULL) {
      dust_volatility_set_state(private$ptr, state, step)
    },

    reset = function(data, step) {
      private$data <- dust_volatility_reset(private$ptr, data, step)
      invisible()
    },

    state = function(index = NULL) {
      dust_volatility_state(private$ptr, index)
    },

    step = function() {
      dust_volatility_step(private$ptr)
    },

    reorder = function(index) {
      dust_volatility_reorder(private$ptr, as.integer(index))
      invisible()
    },

    info = function() {
      private$data
    },

    rng_state = function() {
      dust_volatility_rng_state(private$ptr)
    }
  ))
