#!/bin/bash
set -ex
(cd sphinx && doxygen)
make -C sphinx/examples
mkdir -p sphinx/_static
# It would be nice to write
#    make -C sphinx html SPHINXOPTS="-W --keep-going -n"
# which is "fail on warning, find all warnings" however, there's some
# configuration drama that needs fighting first.
make -C sphinx html
