#!/usr/bin/env Rscript
req <- c("R6", "cpp11", "glue", "pkgbuild", "withr", "brio", "decor",
         "fs", "pkgload", "docopt", "remotes")
msg <- setdiff(req, .packages(TRUE))
install.packages(msg)
err <- setdiff(msg, .packages(TRUE))
if (length(err) > 0L) {
  stop("Failed to install package: ", paste(err, collapse = ", "))
}
remotes::install_local(".", force = TRUE)
