#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
ROOT=$(realpath $HERE/..)
NAME=$1
HASH=$(git -C $ROOT rev-parse --short HEAD)
DEST="${ROOT}/profiles/${NAME}-compute-${HASH}"

mkdir -p $ROOT/profiles/

mkdir -p /raid/${SLURM_JOBID}/tmp
export TMPDIR=/raid/${SLURM_JOBID}/tmp

ncu -o "$DEST" --set full --target-processes all \
    $ROOT/scripts/target_compute_pkg ${NAME} --particles=51200
