#!/usr/bin/env Rscript
examples <- c("sir.cpp", "sirs.cpp", "variable.cpp", "volatility.cpp",
              "walk.cpp")
setwd(here::here())
unlink(file.path("src", examples))
unlink("src/dust.cpp")
unlink("R/dust.R")
cpp11::cpp_register()
