#!/usr/bin/env Rscript
"Usage:
  profile_compute [options] <model>

Options:
  --particles=PARTICLES  Number of particles [default: 100000]
  --steps=STEPS          Number of steps [default: 1000]
" -> usage

main <- function(args = commandArgs(TRUE)) {
  args <- docopt::docopt(usage, args)
  gen_g <- dust::dust(args$model, gpu = TRUE)
  mod_g <- gen_g$new(list(), 0L, as.integer(args$particles))
  y_g <- mod_g$run(as.integer(args$steps))
  invisible(NULL)
}

main()
