#!/usr/bin/env Rscript
"Usage:
  target_compute_pkg [options] <model>

Options:
  --particles=PARTICLES  Number of particles [default: 100000]
  --steps=STEPS          Number of steps [default: 1000]
" -> usage

main <- function(args = commandArgs(TRUE)) {
  args <- docopt::docopt(usage, args)

  if (args$model == "volatility") {
    mod <- gpupkg:::volatility$new(list(), 0L, as.integer(args$particles))
  } else if (args$model == "sirs") {
    mod <- gpupkg:::sirs$new(list(), 0L, as.integer(args$particles))
  } else {
    stop(sprintf("Unknown model '%s'", args$model))
  }
  y <- mod$run(as.integer(args$steps))
  invisible(NULL)
}


main()
