#!/usr/bin/env Rscript
"Usage:
  target_system_pkg [options] <model>

Options:
  --particles=PARTICLES  Number of particles [default: 100000]
" -> usage

main <- function(args = commandArgs(TRUE)) {
  args <- docopt::docopt(usage, args)

  if (args$model == "volatility") {
    mod <- gpupkg:::volatility$new(list(), 0L, as.integer(args$particles))
  } else if (args$model == "sirs") {
    mod <- gpupkg:::sirs$new(list(), 0L, as.integer(args$particles))
  } else {
    stop(sprintf("Unknown model '%s'", args$model))
  }

  mod$set_index(1L)
  times <- seq(10, 50, by = 10)
  for (t in times) {
    y <- mod$run(t)
  }

  invisible(NULL)
}

main()
