#!/usr/bin/env Rscript
"Usage:
  profile_compute [options]

Options:
  --particles=PARTICLES  Number of particles [default: 100000]
  --steps=STEPS          Number of steps [default: 1000]
" -> usage

main <- function(args = commandArgs(TRUE)) {
  args <- docopt::docopt(usage, args)
  mod <- gpupkg:::volatility$new(list(), 0L, as.integer(args$particles))
  y <- mod$run(as.integer(args$steps))
  invisible(NULL)
}

main()
