#!/usr/bin/env Rscript
examples <- c("sir.cpp", "sirs.cpp", "variable.cpp", "volatility.cpp",
              "walk.cpp", "ode/logistic.cpp")

setwd(here::here())
unlink(file.path("src", examples))

pkgload::load_all()
path <- withr::with_dir("tests/testthat",
                        create_test_package(examples = examples))
path <- dust_package(path, quiet = TRUE)
file.copy(file.path(path, "R", "dust.R"), "R", overwrite = TRUE)
unlink(file.path(path, "src", "cpp11.cpp"))
unlink(file.path(path, "src", "Makevars"))
file.copy(dir(file.path(path, "src"), full.names = TRUE), "src",
          overwrite = TRUE)
cpp11::cpp_register()
