#!/usr/bin/env bash
set -eu
HERE=$(dirname $0)
ROOT=$(realpath $HERE/..)

CUB_VERSION=1.9.10
CUB_URL="https://github.com/NVlabs/cub/archive/${CUB_VERSION}.tar.gz"
DEST=$ROOT/inst/include/cub.tar.gz

rm -rf $ROOT/inst/include/cub $DEST

curl -L "$CUB_URL" --output $DEST
(cd $ROOT/inst/include && tar -zxvf $DEST)

mv $ROOT/inst/include/cub-${CUB_VERSION}/cub $ROOT/inst/include
mv $ROOT/inst/include/cub-${CUB_VERSION}/LICENSE.TXT $ROOT/inst/include/cub
rm -rf $ROOT/inst/include/cub-${CUB_VERSION} $DEST

echo "Installed cub '${CUB_VERSION}' into dust (@ ${ROOT}/inst/include/cub)"
