#!/usr/bin/env Rscript
local({
  ## Getting the root could be done better with here::here but we
  ## really want the root relative to the script.
  root <- getwd()
  cub_version <- "1.9.10"
  url <- sprintf("https://github.com/NVlabs/cub/archive/%s.tar.gz", cub_version)
  tgz <- tempfile(fileext = ".tar.gz")
  download.file(url, tgz)
  tmp <- tempfile()
  untar(tgz, exdir = tmp)
  path <- dir(tmp, full.names = TRUE)
  dest <- file.path(root, "inst/include/cub")
  unlink(dest, recursive = TRUE)
  file.copy(file.path(path, "cub"), "inst/include", recursive = TRUE)
  file.copy(file.path(path, "LICENSE.TXT"), "inst/include/cub")
  message(sprintf("Installed cub '%s' into dust (@ %s)",
                  cub_version, dest))
})
