// Generated by dust (version 0.7.6) - do not edit
#include <iostream>
#include <dust/dust.hpp>
#include <dust/interface.hpp>

class sir {
public:
  typedef double real_t;
  struct data_t {
    real_t incidence;
  };
  typedef dust::no_internal internal_t;

  struct shared_t {
    real_t S0;
    real_t I0;
    real_t R0;
    real_t beta;
    real_t gamma;
    real_t dt;
    size_t freq;
    // Observation parameters
    real_t exp_noise;
  };

  sir(const dust::pars_t<sir>& pars) : shared(pars.shared) {
  }

  size_t size() const {
    return 5;
  }

  std::vector<real_t> initial(size_t step) {
    std::vector<real_t> ret = {shared->S0, shared->I0, shared->R0, 0, 0};
    return ret;
  }

  void update(size_t step, const real_t * state,
              dust::rng_state_t<real_t>& rng_state,
              real_t * state_next) {
    real_t S = state[0];
    real_t I = state[1];
    real_t R = state[2];
    real_t cumulative_incidence = state[3];

    real_t N = S + I + R;

    real_t p_SI = 1 - std::exp(-(shared->beta) * I / N);
    real_t p_IR = 1 - std::exp(-(shared->gamma));
    real_t n_IR = dust::distr::rbinom(rng_state, I, p_IR * shared->dt);
    real_t n_SI = dust::distr::rbinom(rng_state, S, p_SI * shared->dt);

    state_next[0] = S - n_SI;
    state_next[1] = I + n_SI - n_IR;
    state_next[2] = R + n_IR;
    state_next[3] = cumulative_incidence + n_SI;
    // Little trick here to compute daily incidence by accumulating
    // incidence from the first day.
    state_next[4] = (step % shared->freq == 0) ? n_SI : state[4] + n_SI;
  }

  real_t compare_data(const real_t * state, const data_t& data,
                      dust::rng_state_t<real_t>& rng_state) {
    const real_t incidence_modelled = state[4];
    const real_t incidence_observed = data.incidence;
    const real_t lambda = incidence_modelled +
      dust::distr::rexp(rng_state, shared->exp_noise);
    return dust::dpois(incidence_observed, lambda, true);
  }

private:
  dust::shared_ptr<sir> shared;
};

#include <cpp11/list.hpp>

// Helper function for accepting values with defaults
inline double with_default(double default_value, cpp11::sexp value) {
  return value == R_NilValue ? default_value : cpp11::as_cpp<double>(value);
}

template <>
dust::pars_t<sir> dust_pars<sir>(cpp11::list pars) {
  typedef sir::real_t real_t;
  // Initial state values
  real_t I0 = 10.0;
  real_t S0 = 1000.0;
  real_t R0 = 0.0;

  // Rates, which can be set based on the provided pars
  // [[dust::param(beta, required = FALSE)]]
  real_t beta = with_default(0.2, pars["beta"]);
  // [[dust::param(gamma, required = FALSE)]]
  real_t gamma = with_default(0.1, pars["gamma"]);

  // Time scaling
  size_t freq = 4;
  real_t dt = 1.0 / static_cast<real_t>(freq);

  // Compare function
  // [[dust::param(exp_noise, required = FALSE)]]
  real_t exp_noise = with_default(1e6, pars["exp_noise"]);

  sir::shared_t shared{S0, I0, R0, beta, gamma, dt, freq, exp_noise};
  return dust::pars_t<sir>(shared);
}

template <>
cpp11::sexp dust_info<sir>(const dust::pars_t<sir>& pars) {
  using namespace cpp11::literals;
  // Information about state order
  cpp11::writable::strings vars({"S", "I", "R", "cases_cumul", "cases_inc"});
  // Information about parameter values
  cpp11::list p = cpp11::writable::list({"beta"_nm = pars.shared->beta,
                                         "gamma"_nm = pars.shared->gamma});
  return cpp11::writable::list({"vars"_nm = vars, "pars"_nm = p});
}

// The way that this is going to work is we will process a list
// *outside* of the C that will take (say) a df and convert it
// row-wise into a list with elements `step` and `data`, we will pass
// that in here. Then this function will be called once per data
// element to create the struct that will be used for future work.
template <>
sir::data_t dust_data<sir>(cpp11::list data) {
  return sir::data_t{cpp11::as_cpp<double>(data["incidence"])};
}

[[cpp11::register]]
SEXP dust_sir_alloc(cpp11::list r_pars, bool pars_multi, size_t step,
                         size_t n_particles, size_t n_threads,
                         cpp11::sexp r_seed) {
  return dust_alloc<sir>(r_pars, pars_multi, step, n_particles,
                               n_threads, r_seed);
}

[[cpp11::register]]
SEXP dust_sir_run(SEXP ptr, size_t step_end) {
  return dust_run<sir>(ptr, step_end);
}

[[cpp11::register]]
SEXP dust_sir_set_index(SEXP ptr, cpp11::sexp r_index) {
  dust_set_index<sir>(ptr, r_index);
  return R_NilValue;
}

[[cpp11::register]]
SEXP dust_sir_set_state(SEXP ptr, SEXP r_state, SEXP r_step) {
  dust_set_state<sir>(ptr, r_state, r_step);
  return R_NilValue;
}

[[cpp11::register]]
SEXP dust_sir_reset(SEXP ptr, cpp11::list r_pars, size_t step) {
  return dust_reset<sir>(ptr, r_pars, step);
}

[[cpp11::register]]
SEXP dust_sir_state(SEXP ptr, SEXP r_index) {
  return dust_state<sir>(ptr, r_index);
}

[[cpp11::register]]
size_t dust_sir_step(SEXP ptr) {
  return dust_step<sir>(ptr);
}

[[cpp11::register]]
void dust_sir_reorder(SEXP ptr, cpp11::sexp r_index) {
  return dust_reorder<sir>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust_sir_resample(SEXP ptr, cpp11::doubles r_weights) {
  return dust_resample<sir>(ptr, r_weights);
}

[[cpp11::register]]
SEXP dust_sir_set_pars(SEXP ptr, cpp11::list r_pars) {
  return dust_set_pars<sir>(ptr, r_pars);
}

[[cpp11::register]]
SEXP dust_sir_rng_state(SEXP ptr, bool first_only) {
  return dust_rng_state<sir>(ptr, first_only);
}

[[cpp11::register]]
SEXP dust_sir_set_rng_state(SEXP ptr, cpp11::raws rng_state) {
  dust_set_rng_state<sir>(ptr, rng_state);
  return R_NilValue;
}

[[cpp11::register]]
SEXP dust_sir_set_data(SEXP ptr, cpp11::list data) {
  dust_set_data<sir>(ptr, data);
  return R_NilValue;
}

[[cpp11::register]]
SEXP dust_sir_compare_data(SEXP ptr) {
  return dust_compare_data<sir>(ptr);
}

[[cpp11::register]]
SEXP dust_sir_filter(SEXP ptr, bool save_history) {
  return dust_filter<sir>(ptr, save_history);
}

[[cpp11::register]]
SEXP dust_sir_simulate(cpp11::sexp r_steps,
                            cpp11::list r_pars,
                            cpp11::doubles_matrix r_state,
                            cpp11::sexp r_index,
                            const size_t n_threads,
                            cpp11::sexp r_seed,
                            bool return_state) {
  return dust_simulate<sir>(r_steps, r_pars, r_state, r_index,
                                  n_threads, r_seed, return_state);
}

[[cpp11::register]]
cpp11::sexp dust_sir_capabilities() {
  return dust_capabilities<sir>();
}

[[cpp11::register]]
void dust_sir_set_n_threads(SEXP ptr, int n_threads) {
  return dust_set_n_threads<sir>(ptr, n_threads);
}

[[cpp11::register]]
int dust_sir_n_state(SEXP ptr) {
  return dust_n_state<sir>(ptr);
}
