// Generated by dust (version 0.11.3) - do not edit
#include <cpp11.hpp>

[[cpp11::register]]
cpp11::sexp dust_sirs_capabilities();

[[cpp11::register]]
cpp11::sexp dust_sirs_gpu_info();
[[cpp11::register]]
SEXP dust_cpu_sirs_alloc(cpp11::list r_pars, bool pars_multi, size_t step,
                         cpp11::sexp r_n_particles, size_t n_threads,
                         cpp11::sexp r_seed, bool deterministic,
                         cpp11::sexp device_config);

[[cpp11::register]]
SEXP dust_cpu_sirs_run(SEXP ptr, size_t step_end);

[[cpp11::register]]
SEXP dust_cpu_sirs_simulate(SEXP ptr, cpp11::sexp step_end);

[[cpp11::register]]
SEXP dust_cpu_sirs_set_index(SEXP ptr, cpp11::sexp r_index);

[[cpp11::register]]
SEXP dust_cpu_sirs_update_state(SEXP ptr, SEXP r_pars, SEXP r_state,
                                SEXP r_step, SEXP r_set_initial_state);

[[cpp11::register]]
SEXP dust_cpu_sirs_state(SEXP ptr, SEXP r_index);

[[cpp11::register]]
size_t dust_cpu_sirs_step(SEXP ptr);

[[cpp11::register]]
void dust_cpu_sirs_reorder(SEXP ptr, cpp11::sexp r_index);

[[cpp11::register]]
SEXP dust_cpu_sirs_resample(SEXP ptr, cpp11::doubles r_weights);

[[cpp11::register]]
SEXP dust_cpu_sirs_rng_state(SEXP ptr, bool first_only, bool last_only);

[[cpp11::register]]
SEXP dust_cpu_sirs_set_rng_state(SEXP ptr, cpp11::raws rng_state);

[[cpp11::register]]
SEXP dust_cpu_sirs_set_data(SEXP ptr, cpp11::list data);

[[cpp11::register]]
SEXP dust_cpu_sirs_compare_data(SEXP ptr);

[[cpp11::register]]
SEXP dust_cpu_sirs_filter(SEXP ptr, bool save_trajectories,
                          cpp11::sexp step_snapshot);

[[cpp11::register]]
void dust_cpu_sirs_set_n_threads(SEXP ptr, int n_threads);

[[cpp11::register]]
int dust_cpu_sirs_n_state(SEXP ptr);
[[cpp11::register]]
SEXP dust_gpu_sirs_alloc(cpp11::list r_pars, bool pars_multi, size_t step,
                         cpp11::sexp r_n_particles, size_t n_threads,
                         cpp11::sexp r_seed, bool deterministic,
                         cpp11::sexp device_config);

[[cpp11::register]]
SEXP dust_gpu_sirs_run(SEXP ptr, size_t step_end);

[[cpp11::register]]
SEXP dust_gpu_sirs_simulate(SEXP ptr, cpp11::sexp step_end);

[[cpp11::register]]
SEXP dust_gpu_sirs_set_index(SEXP ptr, cpp11::sexp r_index);

[[cpp11::register]]
SEXP dust_gpu_sirs_update_state(SEXP ptr, SEXP r_pars, SEXP r_state,
                                SEXP r_step, SEXP r_set_initial_state);

[[cpp11::register]]
SEXP dust_gpu_sirs_state(SEXP ptr, SEXP r_index);

[[cpp11::register]]
size_t dust_gpu_sirs_step(SEXP ptr);

[[cpp11::register]]
void dust_gpu_sirs_reorder(SEXP ptr, cpp11::sexp r_index);

[[cpp11::register]]
SEXP dust_gpu_sirs_resample(SEXP ptr, cpp11::doubles r_weights);

[[cpp11::register]]
SEXP dust_gpu_sirs_rng_state(SEXP ptr, bool first_only, bool last_only);

[[cpp11::register]]
SEXP dust_gpu_sirs_set_rng_state(SEXP ptr, cpp11::raws rng_state);

[[cpp11::register]]
SEXP dust_gpu_sirs_set_data(SEXP ptr, cpp11::list data);

[[cpp11::register]]
SEXP dust_gpu_sirs_compare_data(SEXP ptr);

[[cpp11::register]]
SEXP dust_gpu_sirs_filter(SEXP ptr, bool save_trajectories,
                          cpp11::sexp step_snapshot);

[[cpp11::register]]
void dust_gpu_sirs_set_n_threads(SEXP ptr, int n_threads);

[[cpp11::register]]
int dust_gpu_sirs_n_state(SEXP ptr);
#include <dust/interface/dust.hpp>

class sirs {
public:
  typedef double real_type;
  typedef dust::no_internal internal_type;
  typedef dust::random::generator<real_type> rng_state_type;

  // ALIGN(16) is required before the data_type definition when using NVCC
  // This is so when loaded into shared memory it is aligned correctly
  struct ALIGN(16) data_type {
    double incidence;
  };

  struct shared_type {
    real_type S0;
    real_type I0;
    real_type R0;
    real_type alpha;
    real_type beta;
    real_type gamma;
    real_type dt;
    size_t freq;
    real_type exp_noise;
  };

  sirs(const dust::pars_type<sirs>& pars): shared(pars.shared) {
  }

  size_t size() {
    return 4;
  }

  std::vector<real_type> initial(size_t step) {
    std::vector<real_type> state(4);
    state[0] = shared->S0;
    state[1] = shared->I0;
    state[2] = shared->R0;
    state[3] = 0;
    return state;
  }

  void update(size_t step, const real_type * state, rng_state_type& rng_state,
              real_type * state_next) {
    real_type S = state[0];
    real_type I = state[1];
    real_type R = state[2];
    real_type N = S + I + R;

    real_type p_SI = 1 - exp(- shared->beta * I / N);
    real_type p_IR = 1 - exp(-(shared->gamma));
    real_type p_RS = 1 - exp(- shared->alpha);

    real_type dt = shared->dt;
    real_type n_SI = dust::random::binomial<real_type>(rng_state, S, p_SI * dt);
    real_type n_IR = dust::random::binomial<real_type>(rng_state, I, p_IR * dt);
    real_type n_RS = dust::random::binomial<real_type>(rng_state, R, p_RS * dt);

    state_next[0] = S - n_SI + n_RS;
    state_next[1] = I + n_SI - n_IR;
    state_next[2] = R + n_IR - n_RS;
    state_next[3] = (step % shared->freq == 0) ? n_SI : state[3] + n_SI;
  }

  real_type compare_data(const real_type * state, const data_type& data,
                      rng_state_type& rng_state) {
    const real_type incidence_modelled = state[3];
    const real_type incidence_observed = data.incidence;
    const real_type lambda = incidence_modelled +
      dust::random::exponential<real_type>(rng_state, shared->exp_noise);
    return dust::density::poisson(incidence_observed, lambda, true);
  }

private:
  dust::shared_ptr<sirs> shared;
};

// Helper function for accepting values with defaults
inline double with_default(double default_value, cpp11::sexp value) {
  return value == R_NilValue ? default_value : cpp11::as_cpp<double>(value);
}

namespace dust {
template <>
dust::pars_type<sirs> dust_pars<sirs>(cpp11::list pars) {
  // Initial state values
  sirs::real_type I0 = 10.0;
  sirs::real_type S0 = 1000.0;
  sirs::real_type R0 = 0.0;

  // Time scaling
  // [[dust::param(freq, required = FALSE, default = 1)]]
  size_t freq = std::max(1.0, with_default(1.0, pars["freq"]));
  sirs::real_type dt = 1 / static_cast<sirs::real_type>(freq);

  sirs::real_type exp_noise = 1e6;

  // [[dust::param(alpha, required = FALSE, default = 0.1)]]
  sirs::real_type alpha = with_default(0.1, pars["alpha"]);

  // [[dust::param(beta, required = FALSE, default = 0.2)]]
  sirs::real_type beta = with_default(0.2, pars["beta"]);

  // [[dust::param(gamma, required = FALSE, default = 0.1)]]
  sirs::real_type gamma = with_default(0.1, pars["gamma"]);

  sirs::shared_type shared{S0, I0, R0, alpha, beta, gamma, dt, freq, exp_noise};
  return dust::pars_type<sirs>(shared);
}

template <>
sirs::data_type dust_data<sirs>(cpp11::list data) {
  return sirs::data_type{cpp11::as_cpp<double>(data["incidence"])};
}

namespace cuda {

template <>
size_t device_shared_int_size<sirs>(dust::shared_ptr<sirs> shared) {
  return 1;
}

template <>
size_t device_shared_real_size<sirs>(dust::shared_ptr<sirs> shared) {
  return 5;
}

template <>
void device_shared_copy<sirs>(dust::shared_ptr<sirs> shared,
                              int * shared_int,
                              sirs::real_type * shared_real) {
  typedef sirs::real_type real_type;
  using dust::cuda::shared_copy;
  shared_real = shared_copy<real_type>(shared_real, shared->alpha);
  shared_real = shared_copy<real_type>(shared_real, shared->beta);
  shared_real = shared_copy<real_type>(shared_real, shared->gamma);
  shared_real = shared_copy<real_type>(shared_real, shared->dt);
  shared_real = shared_copy<real_type>(shared_real, shared->exp_noise);
  shared_int = shared_copy<int>(shared_int, shared->freq);
}

template <>
DEVICE
void update_device<sirs>(size_t step,
                         const dust::cuda::interleaved<sirs::real_type> state,
                         dust::cuda::interleaved<int> internal_int,
                         dust::cuda::interleaved<sirs::real_type> internal_real,
                         const int * shared_int,
                         const sirs::real_type * shared_real,
                         sirs::rng_state_type& rng_state,
                         dust::cuda::interleaved<sirs::real_type> state_next) {
  typedef sirs::real_type real_type;
  const real_type alpha = shared_real[0];
  const real_type beta = shared_real[1];
  const real_type gamma = shared_real[2];
  const real_type dt = shared_real[3];
  const int freq = shared_int[0];
  const real_type S = state[0];
  const real_type I = state[1];
  const real_type R = state[2];
  const real_type N = S + I + R;
  const real_type p_SI = 1 - exp(- beta * I / N);
  const real_type p_IR = 1 - exp(- gamma);
  const real_type p_RS = 1 - exp(- alpha);
  const real_type n_SI = dust::random::binomial<real_type>(rng_state, S, p_SI * dt);
  const real_type n_IR = dust::random::binomial<real_type>(rng_state, I, p_IR * dt);
  const real_type n_RS = dust::random::binomial<real_type>(rng_state, R, p_RS * dt);
  state_next[0] = S - n_SI + n_RS;
  state_next[1] = I + n_SI - n_IR;
  state_next[2] = R + n_IR - n_RS;
  state_next[3] = (step % freq == 0) ? n_SI : state[3] + n_SI;
}

template <>
DEVICE
sirs::real_type compare_device<sirs>(const dust::cuda::interleaved<sirs::real_type> state,
                                     const sirs::data_type& data,
                                     dust::cuda::interleaved<int> internal_int,
                                     dust::cuda::interleaved<sirs::real_type> internal_real,
                                     const int * shared_int,
                                     const sirs::real_type * shared_real,
                                     sirs::rng_state_type& rng_state) {
  typedef sirs::real_type real_type;
  const real_type exp_noise = shared_real[4];
  const real_type incidence_modelled = state[3];
  const real_type incidence_observed = data.incidence;
  const real_type lambda = incidence_modelled +
    dust::random::exponential<real_type>(rng_state, exp_noise);
  return dust::density::poisson(incidence_observed, lambda, true);
}

}
}

cpp11::sexp dust_sirs_capabilities() {
  return dust::r::dust_capabilities<sirs>();
}

cpp11::sexp dust_sirs_gpu_info() {
  return dust::cuda::interface::gpu_info<sirs::real_type>();
}
using model_cpu = dust::dust_cpu<sirs>;

SEXP dust_cpu_sirs_alloc(cpp11::list r_pars, bool pars_multi, size_t step,
                             cpp11::sexp r_n_particles, size_t n_threads,
                             cpp11::sexp r_seed, bool deterministic,
                             cpp11::sexp device_config) {
  return dust::r::dust_cpu_alloc<sirs>(r_pars, pars_multi, step, r_n_particles,
                                        n_threads, r_seed, deterministic,
                                        device_config);
}

SEXP dust_cpu_sirs_run(SEXP ptr, size_t step_end) {
  return dust::r::dust_run<model_cpu>(ptr, step_end);
}

SEXP dust_cpu_sirs_simulate(SEXP ptr, cpp11::sexp step_end) {
  return dust::r::dust_simulate<model_cpu>(ptr, step_end);
}

SEXP dust_cpu_sirs_set_index(SEXP ptr, cpp11::sexp r_index) {
  dust::r::dust_set_index<model_cpu>(ptr, r_index);
  return R_NilValue;
}

SEXP dust_cpu_sirs_update_state(SEXP ptr, SEXP r_pars, SEXP r_state,
                                SEXP r_step, SEXP r_set_initial_state) {
  return dust::r::dust_update_state<model_cpu>(ptr, r_pars, r_state, r_step,
                                               r_set_initial_state);
}

SEXP dust_cpu_sirs_state(SEXP ptr, SEXP r_index) {
  return dust::r::dust_state<model_cpu>(ptr, r_index);
}

size_t dust_cpu_sirs_step(SEXP ptr) {
  return dust::r::dust_step<model_cpu>(ptr);
}

void dust_cpu_sirs_reorder(SEXP ptr, cpp11::sexp r_index) {
  return dust::r::dust_reorder<model_cpu>(ptr, r_index);
}

SEXP dust_cpu_sirs_resample(SEXP ptr, cpp11::doubles r_weights) {
  return dust::r::dust_resample<model_cpu>(ptr, r_weights);
}

SEXP dust_cpu_sirs_rng_state(SEXP ptr, bool first_only, bool last_only) {
  return dust::r::dust_rng_state<model_cpu>(ptr, first_only, last_only);
}

SEXP dust_cpu_sirs_set_rng_state(SEXP ptr, cpp11::raws rng_state) {
  dust::r::dust_set_rng_state<model_cpu>(ptr, rng_state);
  return R_NilValue;
}

SEXP dust_cpu_sirs_set_data(SEXP ptr, cpp11::list data) {
  dust::r::dust_set_data<model_cpu>(ptr, data);
  return R_NilValue;
}

SEXP dust_cpu_sirs_compare_data(SEXP ptr) {
  return dust::r::dust_compare_data<model_cpu>(ptr);
}

SEXP dust_cpu_sirs_filter(SEXP ptr, bool save_trajectories,
                          cpp11::sexp step_snapshot) {
  return dust::r::dust_filter<model_cpu>(ptr, save_trajectories, step_snapshot);
}

void dust_cpu_sirs_set_n_threads(SEXP ptr, int n_threads) {
  return dust::r::dust_set_n_threads<model_cpu>(ptr, n_threads);
}

int dust_cpu_sirs_n_state(SEXP ptr) {
  return dust::r::dust_n_state<model_cpu>(ptr);
}
using model_gpu = dust::dust_gpu<sirs>;

SEXP dust_gpu_sirs_alloc(cpp11::list r_pars, bool pars_multi, size_t step,
                             cpp11::sexp r_n_particles, size_t n_threads,
                             cpp11::sexp r_seed, bool deterministic,
                             cpp11::sexp device_config) {
  return dust::r::dust_gpu_alloc<sirs>(r_pars, pars_multi, step, r_n_particles,
                                        n_threads, r_seed, deterministic,
                                        device_config);
}

SEXP dust_gpu_sirs_run(SEXP ptr, size_t step_end) {
  return dust::r::dust_run<model_gpu>(ptr, step_end);
}

SEXP dust_gpu_sirs_simulate(SEXP ptr, cpp11::sexp step_end) {
  return dust::r::dust_simulate<model_gpu>(ptr, step_end);
}

SEXP dust_gpu_sirs_set_index(SEXP ptr, cpp11::sexp r_index) {
  dust::r::dust_set_index<model_gpu>(ptr, r_index);
  return R_NilValue;
}

SEXP dust_gpu_sirs_update_state(SEXP ptr, SEXP r_pars, SEXP r_state,
                                SEXP r_step, SEXP r_set_initial_state) {
  return dust::r::dust_update_state<model_gpu>(ptr, r_pars, r_state, r_step,
                                               r_set_initial_state);
}

SEXP dust_gpu_sirs_state(SEXP ptr, SEXP r_index) {
  return dust::r::dust_state<model_gpu>(ptr, r_index);
}

size_t dust_gpu_sirs_step(SEXP ptr) {
  return dust::r::dust_step<model_gpu>(ptr);
}

void dust_gpu_sirs_reorder(SEXP ptr, cpp11::sexp r_index) {
  return dust::r::dust_reorder<model_gpu>(ptr, r_index);
}

SEXP dust_gpu_sirs_resample(SEXP ptr, cpp11::doubles r_weights) {
  return dust::r::dust_resample<model_gpu>(ptr, r_weights);
}

SEXP dust_gpu_sirs_rng_state(SEXP ptr, bool first_only, bool last_only) {
  return dust::r::dust_rng_state<model_gpu>(ptr, first_only, last_only);
}

SEXP dust_gpu_sirs_set_rng_state(SEXP ptr, cpp11::raws rng_state) {
  dust::r::dust_set_rng_state<model_gpu>(ptr, rng_state);
  return R_NilValue;
}

SEXP dust_gpu_sirs_set_data(SEXP ptr, cpp11::list data) {
  dust::r::dust_set_data<model_gpu>(ptr, data);
  return R_NilValue;
}

SEXP dust_gpu_sirs_compare_data(SEXP ptr) {
  return dust::r::dust_compare_data<model_gpu>(ptr);
}

SEXP dust_gpu_sirs_filter(SEXP ptr, bool save_trajectories,
                          cpp11::sexp step_snapshot) {
  return dust::r::dust_filter<model_gpu>(ptr, save_trajectories, step_snapshot);
}

void dust_gpu_sirs_set_n_threads(SEXP ptr, int n_threads) {
  return dust::r::dust_set_n_threads<model_gpu>(ptr, n_threads);
}

int dust_gpu_sirs_n_state(SEXP ptr) {
  return dust::r::dust_n_state<model_gpu>(ptr);
}
