# Generated by cpp11: do not edit by hand

dust_dbinom <- function(x, size, prob, log) {
  .Call(`_dust_dust_dbinom`, x, size, prob, log)
}

dust_dnbinom <- function(x, size, mu, log) {
  .Call(`_dust_dust_dnbinom`, x, size, mu, log)
}

dust_dbetabinom <- function(x, size, prob, rho, log) {
  .Call(`_dust_dust_dbetabinom`, x, size, prob, rho, log)
}

dust_dpois <- function(x, lambda, log) {
  .Call(`_dust_dust_dpois`, x, lambda, log)
}

dust_rng_alloc <- function(r_seed, n_generators) {
  .Call(`_dust_dust_rng_alloc`, r_seed, n_generators)
}

dust_rng_size <- function(ptr) {
  .Call(`_dust_dust_rng_size`, ptr)
}

dust_rng_jump <- function(ptr) {
  invisible(.Call(`_dust_dust_rng_jump`, ptr))
}

dust_rng_long_jump <- function(ptr) {
  invisible(.Call(`_dust_dust_rng_long_jump`, ptr))
}

dust_rng_unif_rand <- function(ptr, n) {
  .Call(`_dust_dust_rng_unif_rand`, ptr, n)
}

dust_rng_norm_rand <- function(ptr, n) {
  .Call(`_dust_dust_rng_norm_rand`, ptr, n)
}

dust_rng_runif <- function(ptr, n, r_min, r_max) {
  .Call(`_dust_dust_rng_runif`, ptr, n, r_min, r_max)
}

dust_rng_rexp <- function(ptr, n, r_rate) {
  .Call(`_dust_dust_rng_rexp`, ptr, n, r_rate)
}

dust_rng_rnorm <- function(ptr, n, r_mean, r_sd) {
  .Call(`_dust_dust_rng_rnorm`, ptr, n, r_mean, r_sd)
}

dust_rng_rbinom <- function(ptr, n, r_size, r_prob) {
  .Call(`_dust_dust_rng_rbinom`, ptr, n, r_size, r_prob)
}

dust_rng_rpois <- function(ptr, n, r_lambda) {
  .Call(`_dust_dust_rng_rpois`, ptr, n, r_lambda)
}

dust_rng_state <- function(ptr) {
  .Call(`_dust_dust_rng_state`, ptr)
}

cpp_openmp_info <- function() {
  .Call(`_dust_cpp_openmp_info`)
}
