# Generated by cpp11: do not edit by hand

dust_rng_alloc <- function(seed, n_generators) {
  .Call("_dust_dust_rng_alloc", seed, n_generators)
}

dust_rng_unif_rand <- function(ptr, n) {
  .Call("_dust_dust_rng_unif_rand", ptr, n)
}

