## Generated by dust (version 0.9.11) - do not edit
sir <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    pars_ = NULL,
    pars_multi_ = NULL,
    index_ = NULL,
    info_ = NULL,
    n_threads_ = NULL,
    n_particles_ = NULL,
    n_particles_each_ = NULL,
    shape_ = NULL,
    ptr_ = NULL,
    device_config_ = NULL,
    param_ = list(I0 = list(required = FALSE),
     beta = list(required = FALSE),
     gamma = list(required = FALSE),
     exp_noise = list(required = FALSE))
  ),

  public = list(
    initialize = function(pars, step, n_particles, n_threads = 1L,
                          seed = NULL, pars_multi = FALSE,
                          device_config = NULL) {
      res <- dust_sir_alloc(pars, pars_multi, step, n_particles,
                        n_threads, seed, device_config)
      private$pars_ <- pars
      private$pars_multi_ <- pars_multi
      private$n_threads_ <- n_threads
      private$ptr_ <- res[[1L]]
      private$info_ <- res[[2L]]
      private$shape_ <- res[[3L]]
      private$device_config_ <- res[[4L]]
      private$n_particles_ <- prod(private$shape_)
      if (pars_multi) {
        private$n_particles_each_ <- private$n_particles_ / length(pars)
      } else {
        private$n_particles_each_ <- private$n_particles_
      }
    },

    name = function() {
      "sir"
    },

    param = function() {
      private$param_
    },

    run = function(step_end, device = FALSE, deterministic = FALSE) {
      m <- dust_sir_run(private$ptr_, step_end, device, deterministic)
      rownames(m) <- names(private$index_)
      m
    },

    simulate = function(step_end, device = FALSE, deterministic = FALSE) {
      m <- dust_sir_simulate(private$ptr_, step_end, device)
      rownames(m) <- names(private$index_)
      m
    },

    set_index = function(index) {
      dust_sir_set_index(private$ptr_, index)
      private$index_ <- index
      invisible()
    },

    index = function() {
      private$index_
    },

    n_threads = function() {
      private$n_threads_
    },

    n_state = function() {
      dust_sir_n_state(private$ptr_)
    },

    n_particles = function() {
      private$n_particles_
    },

    n_particles_each = function() {
      private$n_particles_each_
    },

    shape = function() {
      private$shape_
    },

    set_state = function(state, step = NULL, deterministic = FALSE) {
      dust_sir_set_state(private$ptr_, state, step)
      invisible()
    },

    reset = function(pars, step) {
      private$info_ <- dust_sir_reset(private$ptr_, pars, step)
      private$pars_ <- pars
      invisible()
    },

    set_pars = function(pars) {
      private$info_ <- dust_sir_set_pars(private$ptr_, pars)
      private$pars_ <- pars
    },

    state = function(index = NULL) {
      m <- dust_sir_state(private$ptr_, index)
      rownames(m) <- names(index)
      m
    },

    step = function() {
      dust_sir_step(private$ptr_)
    },

    reorder = function(index) {
      storage.mode(index) <- "integer"
      dust_sir_reorder(private$ptr_, index)
      invisible()
    },

    resample = function(weights) {
      invisible(dust_sir_resample(private$ptr_, weights))
    },

    info = function() {
      private$info_
    },

    pars = function() {
      private$pars_
    },

    rng_state = function(first_only = FALSE, last_only = FALSE) {
      dust_sir_rng_state(private$ptr_, first_only, last_only)
    },

    set_rng_state = function(rng_state) {
      dust_sir_set_rng_state(private$ptr_, rng_state)
      invisible()
    },

    has_openmp = function() {
      dust_sir_capabilities()[["openmp"]]
    },

    has_cuda = function() {
      dust_sir_capabilities()[["cuda"]]
    },

    n_pars = function() {
      if (private$pars_multi_) length(private$pars_) else 0L
    },

    set_n_threads = function(n_threads) {
      prev <- private$n_threads_
      dust_sir_set_n_threads(private$ptr_, n_threads)
      private$n_threads_ <- n_threads
      invisible(prev)
    },

    has_compare = function() {
      dust_sir_capabilities()[["compare"]]
    },

    set_data = function(data) {
      dust_sir_set_data(private$ptr_, data)
    },

    compare_data = function(device = FALSE) {
      dust_sir_compare_data(private$ptr_, device)
    },

    filter = function(save_trajectories = FALSE, step_snapshot = NULL,
                      device = FALSE) {
      dust_sir_filter(private$ptr_, save_trajectories,
                           step_snapshot, device)
    },

    device_info = function() {
      ret <- dust_sir_device_info()
      parent <- parent.env(environment())
      if (ret$has_cuda && exists("private", parent, inherits = FALSE)) {
        ret$config <- private$device_config_
      }
      ret
    }
  ))
class(sir) <- c("dust_generator", class(sir))
sirs <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    pars_ = NULL,
    pars_multi_ = NULL,
    index_ = NULL,
    info_ = NULL,
    n_threads_ = NULL,
    n_particles_ = NULL,
    n_particles_each_ = NULL,
    shape_ = NULL,
    ptr_ = NULL,
    device_config_ = NULL,
    param_ = list(freq = list(required = FALSE, default = 1),
     alpha = list(required = FALSE, default = 0.1),
     beta = list(required = FALSE, default = 0.2),
     gamma = list(required = FALSE, default = 0.1))
  ),

  public = list(
    initialize = function(pars, step, n_particles, n_threads = 1L,
                          seed = NULL, pars_multi = FALSE,
                          device_config = NULL) {
      res <- dust_sirs_alloc(pars, pars_multi, step, n_particles,
                        n_threads, seed, device_config)
      private$pars_ <- pars
      private$pars_multi_ <- pars_multi
      private$n_threads_ <- n_threads
      private$ptr_ <- res[[1L]]
      private$info_ <- res[[2L]]
      private$shape_ <- res[[3L]]
      private$device_config_ <- res[[4L]]
      private$n_particles_ <- prod(private$shape_)
      if (pars_multi) {
        private$n_particles_each_ <- private$n_particles_ / length(pars)
      } else {
        private$n_particles_each_ <- private$n_particles_
      }
    },

    name = function() {
      "sirs"
    },

    param = function() {
      private$param_
    },

    run = function(step_end, device = FALSE, deterministic = FALSE) {
      m <- dust_sirs_run(private$ptr_, step_end, device, deterministic)
      rownames(m) <- names(private$index_)
      m
    },

    simulate = function(step_end, device = FALSE, deterministic = FALSE) {
      m <- dust_sirs_simulate(private$ptr_, step_end, device)
      rownames(m) <- names(private$index_)
      m
    },

    set_index = function(index) {
      dust_sirs_set_index(private$ptr_, index)
      private$index_ <- index
      invisible()
    },

    index = function() {
      private$index_
    },

    n_threads = function() {
      private$n_threads_
    },

    n_state = function() {
      dust_sirs_n_state(private$ptr_)
    },

    n_particles = function() {
      private$n_particles_
    },

    n_particles_each = function() {
      private$n_particles_each_
    },

    shape = function() {
      private$shape_
    },

    set_state = function(state, step = NULL, deterministic = FALSE) {
      dust_sirs_set_state(private$ptr_, state, step)
      invisible()
    },

    reset = function(pars, step) {
      private$info_ <- dust_sirs_reset(private$ptr_, pars, step)
      private$pars_ <- pars
      invisible()
    },

    set_pars = function(pars) {
      private$info_ <- dust_sirs_set_pars(private$ptr_, pars)
      private$pars_ <- pars
    },

    state = function(index = NULL) {
      m <- dust_sirs_state(private$ptr_, index)
      rownames(m) <- names(index)
      m
    },

    step = function() {
      dust_sirs_step(private$ptr_)
    },

    reorder = function(index) {
      storage.mode(index) <- "integer"
      dust_sirs_reorder(private$ptr_, index)
      invisible()
    },

    resample = function(weights) {
      invisible(dust_sirs_resample(private$ptr_, weights))
    },

    info = function() {
      private$info_
    },

    pars = function() {
      private$pars_
    },

    rng_state = function(first_only = FALSE, last_only = FALSE) {
      dust_sirs_rng_state(private$ptr_, first_only, last_only)
    },

    set_rng_state = function(rng_state) {
      dust_sirs_set_rng_state(private$ptr_, rng_state)
      invisible()
    },

    has_openmp = function() {
      dust_sirs_capabilities()[["openmp"]]
    },

    has_cuda = function() {
      dust_sirs_capabilities()[["cuda"]]
    },

    n_pars = function() {
      if (private$pars_multi_) length(private$pars_) else 0L
    },

    set_n_threads = function(n_threads) {
      prev <- private$n_threads_
      dust_sirs_set_n_threads(private$ptr_, n_threads)
      private$n_threads_ <- n_threads
      invisible(prev)
    },

    has_compare = function() {
      dust_sirs_capabilities()[["compare"]]
    },

    set_data = function(data) {
      dust_sirs_set_data(private$ptr_, data)
    },

    compare_data = function(device = FALSE) {
      dust_sirs_compare_data(private$ptr_, device)
    },

    filter = function(save_trajectories = FALSE, step_snapshot = NULL,
                      device = FALSE) {
      dust_sirs_filter(private$ptr_, save_trajectories,
                           step_snapshot, device)
    },

    device_info = function() {
      ret <- dust_sirs_device_info()
      parent <- parent.env(environment())
      if (ret$has_cuda && exists("private", parent, inherits = FALSE)) {
        ret$config <- private$device_config_
      }
      ret
    }
  ))
class(sirs) <- c("dust_generator", class(sirs))
variable <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    pars_ = NULL,
    pars_multi_ = NULL,
    index_ = NULL,
    info_ = NULL,
    n_threads_ = NULL,
    n_particles_ = NULL,
    n_particles_each_ = NULL,
    shape_ = NULL,
    ptr_ = NULL,
    device_config_ = NULL,
    param_ = NULL
  ),

  public = list(
    initialize = function(pars, step, n_particles, n_threads = 1L,
                          seed = NULL, pars_multi = FALSE,
                          device_config = NULL) {
      res <- dust_variable_alloc(pars, pars_multi, step, n_particles,
                        n_threads, seed, device_config)
      private$pars_ <- pars
      private$pars_multi_ <- pars_multi
      private$n_threads_ <- n_threads
      private$ptr_ <- res[[1L]]
      private$info_ <- res[[2L]]
      private$shape_ <- res[[3L]]
      private$device_config_ <- res[[4L]]
      private$n_particles_ <- prod(private$shape_)
      if (pars_multi) {
        private$n_particles_each_ <- private$n_particles_ / length(pars)
      } else {
        private$n_particles_each_ <- private$n_particles_
      }
    },

    name = function() {
      "variable"
    },

    param = function() {
      private$param_
    },

    run = function(step_end, device = FALSE, deterministic = FALSE) {
      m <- dust_variable_run(private$ptr_, step_end, device, deterministic)
      rownames(m) <- names(private$index_)
      m
    },

    simulate = function(step_end, device = FALSE, deterministic = FALSE) {
      m <- dust_variable_simulate(private$ptr_, step_end, device)
      rownames(m) <- names(private$index_)
      m
    },

    set_index = function(index) {
      dust_variable_set_index(private$ptr_, index)
      private$index_ <- index
      invisible()
    },

    index = function() {
      private$index_
    },

    n_threads = function() {
      private$n_threads_
    },

    n_state = function() {
      dust_variable_n_state(private$ptr_)
    },

    n_particles = function() {
      private$n_particles_
    },

    n_particles_each = function() {
      private$n_particles_each_
    },

    shape = function() {
      private$shape_
    },

    set_state = function(state, step = NULL, deterministic = FALSE) {
      dust_variable_set_state(private$ptr_, state, step)
      invisible()
    },

    reset = function(pars, step) {
      private$info_ <- dust_variable_reset(private$ptr_, pars, step)
      private$pars_ <- pars
      invisible()
    },

    set_pars = function(pars) {
      private$info_ <- dust_variable_set_pars(private$ptr_, pars)
      private$pars_ <- pars
    },

    state = function(index = NULL) {
      m <- dust_variable_state(private$ptr_, index)
      rownames(m) <- names(index)
      m
    },

    step = function() {
      dust_variable_step(private$ptr_)
    },

    reorder = function(index) {
      storage.mode(index) <- "integer"
      dust_variable_reorder(private$ptr_, index)
      invisible()
    },

    resample = function(weights) {
      invisible(dust_variable_resample(private$ptr_, weights))
    },

    info = function() {
      private$info_
    },

    pars = function() {
      private$pars_
    },

    rng_state = function(first_only = FALSE, last_only = FALSE) {
      dust_variable_rng_state(private$ptr_, first_only, last_only)
    },

    set_rng_state = function(rng_state) {
      dust_variable_set_rng_state(private$ptr_, rng_state)
      invisible()
    },

    has_openmp = function() {
      dust_variable_capabilities()[["openmp"]]
    },

    has_cuda = function() {
      dust_variable_capabilities()[["cuda"]]
    },

    n_pars = function() {
      if (private$pars_multi_) length(private$pars_) else 0L
    },

    set_n_threads = function(n_threads) {
      prev <- private$n_threads_
      dust_variable_set_n_threads(private$ptr_, n_threads)
      private$n_threads_ <- n_threads
      invisible(prev)
    },

    has_compare = function() {
      dust_variable_capabilities()[["compare"]]
    },

    set_data = function(data) {
      dust_variable_set_data(private$ptr_, data)
    },

    compare_data = function(device = FALSE) {
      dust_variable_compare_data(private$ptr_, device)
    },

    filter = function(save_trajectories = FALSE, step_snapshot = NULL,
                      device = FALSE) {
      dust_variable_filter(private$ptr_, save_trajectories,
                           step_snapshot, device)
    },

    device_info = function() {
      ret <- dust_variable_device_info()
      parent <- parent.env(environment())
      if (ret$has_cuda && exists("private", parent, inherits = FALSE)) {
        ret$config <- private$device_config_
      }
      ret
    }
  ))
class(variable) <- c("dust_generator", class(variable))
volatility <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    pars_ = NULL,
    pars_multi_ = NULL,
    index_ = NULL,
    info_ = NULL,
    n_threads_ = NULL,
    n_particles_ = NULL,
    n_particles_each_ = NULL,
    shape_ = NULL,
    ptr_ = NULL,
    device_config_ = NULL,
    param_ = NULL
  ),

  public = list(
    initialize = function(pars, step, n_particles, n_threads = 1L,
                          seed = NULL, pars_multi = FALSE,
                          device_config = NULL) {
      res <- dust_volatility_alloc(pars, pars_multi, step, n_particles,
                        n_threads, seed, device_config)
      private$pars_ <- pars
      private$pars_multi_ <- pars_multi
      private$n_threads_ <- n_threads
      private$ptr_ <- res[[1L]]
      private$info_ <- res[[2L]]
      private$shape_ <- res[[3L]]
      private$device_config_ <- res[[4L]]
      private$n_particles_ <- prod(private$shape_)
      if (pars_multi) {
        private$n_particles_each_ <- private$n_particles_ / length(pars)
      } else {
        private$n_particles_each_ <- private$n_particles_
      }
    },

    name = function() {
      "volatility"
    },

    param = function() {
      private$param_
    },

    run = function(step_end, device = FALSE, deterministic = FALSE) {
      m <- dust_volatility_run(private$ptr_, step_end, device, deterministic)
      rownames(m) <- names(private$index_)
      m
    },

    simulate = function(step_end, device = FALSE, deterministic = FALSE) {
      m <- dust_volatility_simulate(private$ptr_, step_end, device)
      rownames(m) <- names(private$index_)
      m
    },

    set_index = function(index) {
      dust_volatility_set_index(private$ptr_, index)
      private$index_ <- index
      invisible()
    },

    index = function() {
      private$index_
    },

    n_threads = function() {
      private$n_threads_
    },

    n_state = function() {
      dust_volatility_n_state(private$ptr_)
    },

    n_particles = function() {
      private$n_particles_
    },

    n_particles_each = function() {
      private$n_particles_each_
    },

    shape = function() {
      private$shape_
    },

    set_state = function(state, step = NULL, deterministic = FALSE) {
      dust_volatility_set_state(private$ptr_, state, step)
      invisible()
    },

    reset = function(pars, step) {
      private$info_ <- dust_volatility_reset(private$ptr_, pars, step)
      private$pars_ <- pars
      invisible()
    },

    set_pars = function(pars) {
      private$info_ <- dust_volatility_set_pars(private$ptr_, pars)
      private$pars_ <- pars
    },

    state = function(index = NULL) {
      m <- dust_volatility_state(private$ptr_, index)
      rownames(m) <- names(index)
      m
    },

    step = function() {
      dust_volatility_step(private$ptr_)
    },

    reorder = function(index) {
      storage.mode(index) <- "integer"
      dust_volatility_reorder(private$ptr_, index)
      invisible()
    },

    resample = function(weights) {
      invisible(dust_volatility_resample(private$ptr_, weights))
    },

    info = function() {
      private$info_
    },

    pars = function() {
      private$pars_
    },

    rng_state = function(first_only = FALSE, last_only = FALSE) {
      dust_volatility_rng_state(private$ptr_, first_only, last_only)
    },

    set_rng_state = function(rng_state) {
      dust_volatility_set_rng_state(private$ptr_, rng_state)
      invisible()
    },

    has_openmp = function() {
      dust_volatility_capabilities()[["openmp"]]
    },

    has_cuda = function() {
      dust_volatility_capabilities()[["cuda"]]
    },

    n_pars = function() {
      if (private$pars_multi_) length(private$pars_) else 0L
    },

    set_n_threads = function(n_threads) {
      prev <- private$n_threads_
      dust_volatility_set_n_threads(private$ptr_, n_threads)
      private$n_threads_ <- n_threads
      invisible(prev)
    },

    has_compare = function() {
      dust_volatility_capabilities()[["compare"]]
    },

    set_data = function(data) {
      dust_volatility_set_data(private$ptr_, data)
    },

    compare_data = function(device = FALSE) {
      dust_volatility_compare_data(private$ptr_, device)
    },

    filter = function(save_trajectories = FALSE, step_snapshot = NULL,
                      device = FALSE) {
      dust_volatility_filter(private$ptr_, save_trajectories,
                           step_snapshot, device)
    },

    device_info = function() {
      ret <- dust_volatility_device_info()
      parent <- parent.env(environment())
      if (ret$has_cuda && exists("private", parent, inherits = FALSE)) {
        ret$config <- private$device_config_
      }
      ret
    }
  ))
class(volatility) <- c("dust_generator", class(volatility))
walk <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    pars_ = NULL,
    pars_multi_ = NULL,
    index_ = NULL,
    info_ = NULL,
    n_threads_ = NULL,
    n_particles_ = NULL,
    n_particles_each_ = NULL,
    shape_ = NULL,
    ptr_ = NULL,
    device_config_ = NULL,
    param_ = NULL
  ),

  public = list(
    initialize = function(pars, step, n_particles, n_threads = 1L,
                          seed = NULL, pars_multi = FALSE,
                          device_config = NULL) {
      res <- dust_walk_alloc(pars, pars_multi, step, n_particles,
                        n_threads, seed, device_config)
      private$pars_ <- pars
      private$pars_multi_ <- pars_multi
      private$n_threads_ <- n_threads
      private$ptr_ <- res[[1L]]
      private$info_ <- res[[2L]]
      private$shape_ <- res[[3L]]
      private$device_config_ <- res[[4L]]
      private$n_particles_ <- prod(private$shape_)
      if (pars_multi) {
        private$n_particles_each_ <- private$n_particles_ / length(pars)
      } else {
        private$n_particles_each_ <- private$n_particles_
      }
    },

    name = function() {
      "walk"
    },

    param = function() {
      private$param_
    },

    run = function(step_end, device = FALSE, deterministic = FALSE) {
      m <- dust_walk_run(private$ptr_, step_end, device, deterministic)
      rownames(m) <- names(private$index_)
      m
    },

    simulate = function(step_end, device = FALSE, deterministic = FALSE) {
      m <- dust_walk_simulate(private$ptr_, step_end, device)
      rownames(m) <- names(private$index_)
      m
    },

    set_index = function(index) {
      dust_walk_set_index(private$ptr_, index)
      private$index_ <- index
      invisible()
    },

    index = function() {
      private$index_
    },

    n_threads = function() {
      private$n_threads_
    },

    n_state = function() {
      dust_walk_n_state(private$ptr_)
    },

    n_particles = function() {
      private$n_particles_
    },

    n_particles_each = function() {
      private$n_particles_each_
    },

    shape = function() {
      private$shape_
    },

    set_state = function(state, step = NULL, deterministic = FALSE) {
      dust_walk_set_state(private$ptr_, state, step)
      invisible()
    },

    reset = function(pars, step) {
      private$info_ <- dust_walk_reset(private$ptr_, pars, step)
      private$pars_ <- pars
      invisible()
    },

    set_pars = function(pars) {
      private$info_ <- dust_walk_set_pars(private$ptr_, pars)
      private$pars_ <- pars
    },

    state = function(index = NULL) {
      m <- dust_walk_state(private$ptr_, index)
      rownames(m) <- names(index)
      m
    },

    step = function() {
      dust_walk_step(private$ptr_)
    },

    reorder = function(index) {
      storage.mode(index) <- "integer"
      dust_walk_reorder(private$ptr_, index)
      invisible()
    },

    resample = function(weights) {
      invisible(dust_walk_resample(private$ptr_, weights))
    },

    info = function() {
      private$info_
    },

    pars = function() {
      private$pars_
    },

    rng_state = function(first_only = FALSE, last_only = FALSE) {
      dust_walk_rng_state(private$ptr_, first_only, last_only)
    },

    set_rng_state = function(rng_state) {
      dust_walk_set_rng_state(private$ptr_, rng_state)
      invisible()
    },

    has_openmp = function() {
      dust_walk_capabilities()[["openmp"]]
    },

    has_cuda = function() {
      dust_walk_capabilities()[["cuda"]]
    },

    n_pars = function() {
      if (private$pars_multi_) length(private$pars_) else 0L
    },

    set_n_threads = function(n_threads) {
      prev <- private$n_threads_
      dust_walk_set_n_threads(private$ptr_, n_threads)
      private$n_threads_ <- n_threads
      invisible(prev)
    },

    has_compare = function() {
      dust_walk_capabilities()[["compare"]]
    },

    set_data = function(data) {
      dust_walk_set_data(private$ptr_, data)
    },

    compare_data = function(device = FALSE) {
      dust_walk_compare_data(private$ptr_, device)
    },

    filter = function(save_trajectories = FALSE, step_snapshot = NULL,
                      device = FALSE) {
      dust_walk_filter(private$ptr_, save_trajectories,
                           step_snapshot, device)
    },

    device_info = function() {
      ret <- dust_walk_device_info()
      parent <- parent.env(environment())
      if (ret$has_cuda && exists("private", parent, inherits = FALSE)) {
        ret$config <- private$device_config_
      }
      ret
    }
  ))
class(walk) <- c("dust_generator", class(walk))
