## Generated by dust (version 0.5.2) - do not edit
sir <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    data_ = NULL,
    index_ = NULL,
    info_ = NULL,
    n_threads_ = NULL,
    ptr_ = NULL,
    param_ = list(beta = list(required = FALSE), gamma = list(required = FALSE)),

    simulate = function(steps, data, state, index = NULL,
                        n_threads = 1L, seed = NULL) {
      dust_sir_simulate(steps, data, state, index, n_threads, seed)
    }
  ),

  public = list(
    initialize = function(data, step, n_particles, n_threads = 1L,
                          seed = NULL) {
      res <- dust_sir_alloc(data, step, n_particles,
                        n_threads, seed)
      private$data_ <- data
      private$n_threads_ <- n_threads
      private$ptr_ <- res[[1L]]
      private$info_ <- res[[2L]]
    },

    name = function() {
      "sir"
    },

    param = function() {
      private$param_
    },

    run = function(step_end) {
      m <- dust_sir_run(private$ptr_, step_end)
      rownames(m) <- names(private$index_)
      m
    },

    set_index = function(index) {
      dust_sir_set_index(private$ptr_, index)
      private$index_ <- index
      invisible()
    },

    index = function() {
      private$index_
    },

    n_threads = function() {
      private$n_threads_
    },

    set_state = function(state, step = NULL) {
      dust_sir_set_state(private$ptr_, state, step)
    },

    reset = function(data, step) {
      private$info_ <- dust_sir_reset(private$ptr_, data, step)
      private$index_ <- NULL
      private$data_ <- data
      invisible()
    },

    state = function(index = NULL) {
      m <- dust_sir_state(private$ptr_, index)
      rownames(m) <- names(index)
      m
    },

    step = function() {
      dust_sir_step(private$ptr_)
    },

    reorder = function(index) {
      dust_sir_reorder(private$ptr_, as.integer(index))
      invisible()
    },

    info = function() {
      private$info_
    },

    data = function() {
      private$data_
    },

    rng_state = function(first_only = FALSE) {
      dust_sir_rng_state(private$ptr_, first_only)
    },

    set_rng_state = function(rng_state) {
      dust_sir_set_rng_state(private$ptr_, rng_state)
      invisible()
    },

    has_openmp = function() {
      dust_sir_has_openmp()
    }
  ))
class(sir) <- c("dust_generator", class(sir))
variable <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    data_ = NULL,
    index_ = NULL,
    info_ = NULL,
    n_threads_ = NULL,
    ptr_ = NULL,
    param_ = NULL,

    simulate = function(steps, data, state, index = NULL,
                        n_threads = 1L, seed = NULL) {
      dust_variable_simulate(steps, data, state, index, n_threads, seed)
    }
  ),

  public = list(
    initialize = function(data, step, n_particles, n_threads = 1L,
                          seed = NULL) {
      res <- dust_variable_alloc(data, step, n_particles,
                        n_threads, seed)
      private$data_ <- data
      private$n_threads_ <- n_threads
      private$ptr_ <- res[[1L]]
      private$info_ <- res[[2L]]
    },

    name = function() {
      "variable"
    },

    param = function() {
      private$param_
    },

    run = function(step_end) {
      m <- dust_variable_run(private$ptr_, step_end)
      rownames(m) <- names(private$index_)
      m
    },

    set_index = function(index) {
      dust_variable_set_index(private$ptr_, index)
      private$index_ <- index
      invisible()
    },

    index = function() {
      private$index_
    },

    n_threads = function() {
      private$n_threads_
    },

    set_state = function(state, step = NULL) {
      dust_variable_set_state(private$ptr_, state, step)
    },

    reset = function(data, step) {
      private$info_ <- dust_variable_reset(private$ptr_, data, step)
      private$index_ <- NULL
      private$data_ <- data
      invisible()
    },

    state = function(index = NULL) {
      m <- dust_variable_state(private$ptr_, index)
      rownames(m) <- names(index)
      m
    },

    step = function() {
      dust_variable_step(private$ptr_)
    },

    reorder = function(index) {
      dust_variable_reorder(private$ptr_, as.integer(index))
      invisible()
    },

    info = function() {
      private$info_
    },

    data = function() {
      private$data_
    },

    rng_state = function(first_only = FALSE) {
      dust_variable_rng_state(private$ptr_, first_only)
    },

    set_rng_state = function(rng_state) {
      dust_variable_set_rng_state(private$ptr_, rng_state)
      invisible()
    },

    has_openmp = function() {
      dust_variable_has_openmp()
    }
  ))
class(variable) <- c("dust_generator", class(variable))
volatility <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    data_ = NULL,
    index_ = NULL,
    info_ = NULL,
    n_threads_ = NULL,
    ptr_ = NULL,
    param_ = NULL,

    simulate = function(steps, data, state, index = NULL,
                        n_threads = 1L, seed = NULL) {
      dust_volatility_simulate(steps, data, state, index, n_threads, seed)
    }
  ),

  public = list(
    initialize = function(data, step, n_particles, n_threads = 1L,
                          seed = NULL) {
      res <- dust_volatility_alloc(data, step, n_particles,
                        n_threads, seed)
      private$data_ <- data
      private$n_threads_ <- n_threads
      private$ptr_ <- res[[1L]]
      private$info_ <- res[[2L]]
    },

    name = function() {
      "volatility"
    },

    param = function() {
      private$param_
    },

    run = function(step_end) {
      m <- dust_volatility_run(private$ptr_, step_end)
      rownames(m) <- names(private$index_)
      m
    },

    set_index = function(index) {
      dust_volatility_set_index(private$ptr_, index)
      private$index_ <- index
      invisible()
    },

    index = function() {
      private$index_
    },

    n_threads = function() {
      private$n_threads_
    },

    set_state = function(state, step = NULL) {
      dust_volatility_set_state(private$ptr_, state, step)
    },

    reset = function(data, step) {
      private$info_ <- dust_volatility_reset(private$ptr_, data, step)
      private$index_ <- NULL
      private$data_ <- data
      invisible()
    },

    state = function(index = NULL) {
      m <- dust_volatility_state(private$ptr_, index)
      rownames(m) <- names(index)
      m
    },

    step = function() {
      dust_volatility_step(private$ptr_)
    },

    reorder = function(index) {
      dust_volatility_reorder(private$ptr_, as.integer(index))
      invisible()
    },

    info = function() {
      private$info_
    },

    data = function() {
      private$data_
    },

    rng_state = function(first_only = FALSE) {
      dust_volatility_rng_state(private$ptr_, first_only)
    },

    set_rng_state = function(rng_state) {
      dust_volatility_set_rng_state(private$ptr_, rng_state)
      invisible()
    },

    has_openmp = function() {
      dust_volatility_has_openmp()
    }
  ))
class(volatility) <- c("dust_generator", class(volatility))
walk <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    data_ = NULL,
    index_ = NULL,
    info_ = NULL,
    n_threads_ = NULL,
    ptr_ = NULL,
    param_ = NULL,

    simulate = function(steps, data, state, index = NULL,
                        n_threads = 1L, seed = NULL) {
      dust_walk_simulate(steps, data, state, index, n_threads, seed)
    }
  ),

  public = list(
    initialize = function(data, step, n_particles, n_threads = 1L,
                          seed = NULL) {
      res <- dust_walk_alloc(data, step, n_particles,
                        n_threads, seed)
      private$data_ <- data
      private$n_threads_ <- n_threads
      private$ptr_ <- res[[1L]]
      private$info_ <- res[[2L]]
    },

    name = function() {
      "walk"
    },

    param = function() {
      private$param_
    },

    run = function(step_end) {
      m <- dust_walk_run(private$ptr_, step_end)
      rownames(m) <- names(private$index_)
      m
    },

    set_index = function(index) {
      dust_walk_set_index(private$ptr_, index)
      private$index_ <- index
      invisible()
    },

    index = function() {
      private$index_
    },

    n_threads = function() {
      private$n_threads_
    },

    set_state = function(state, step = NULL) {
      dust_walk_set_state(private$ptr_, state, step)
    },

    reset = function(data, step) {
      private$info_ <- dust_walk_reset(private$ptr_, data, step)
      private$index_ <- NULL
      private$data_ <- data
      invisible()
    },

    state = function(index = NULL) {
      m <- dust_walk_state(private$ptr_, index)
      rownames(m) <- names(index)
      m
    },

    step = function() {
      dust_walk_step(private$ptr_)
    },

    reorder = function(index) {
      dust_walk_reorder(private$ptr_, as.integer(index))
      invisible()
    },

    info = function() {
      private$info_
    },

    data = function() {
      private$data_
    },

    rng_state = function(first_only = FALSE) {
      dust_walk_rng_state(private$ptr_, first_only)
    },

    set_rng_state = function(rng_state) {
      dust_walk_set_rng_state(private$ptr_, rng_state)
      invisible()
    },

    has_openmp = function() {
      dust_walk_has_openmp()
    }
  ))
class(walk) <- c("dust_generator", class(walk))
