# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_rng_norm <- function(n, seed, n_generators) {
    .Call(`_dust_test_rng_norm`, n, seed, n_generators)
}

test_rng_unif <- function(n, min, max, seed, n_generators) {
    .Call(`_dust_test_rng_unif`, n, min, max, seed, n_generators)
}

test_rng_binom <- function(n, p, seed, n_generators) {
    .Call(`_dust_test_rng_binom`, n, p, seed, n_generators)
}

test_rng_pois <- function(lambda, seed, n_generators) {
    .Call(`_dust_test_rng_pois`, lambda, seed, n_generators)
}
