`%||%` <- function(a, b) { # nolint
  if (is.null(a)) b else a
}


hash_file <- function(path, short = TRUE) {
  hash <- unname(tools::md5sum(path))
  if (short) {
    hash <- substr(hash, 1, 8)
  }
  hash
}


dust_file <- function(path) {
  system.file(path, package = "dust", mustWork = TRUE)
}


read_lines <- function(path) {
  paste(readLines(path), collapse = "\n")
}


assert_valid_name <- function(x, name = deparse(substitute(x))) {
  if (!grepl("^[A-Za-z][A-Zxa-z0-9]*$", x)) {
    stop(sprintf(
      "'%s' must contain only letters and numbers, starting with a letter",
      name))
  }
}


assert_file_exists <- function(path, name = "File") {
  if (!file.exists(path)) {
    stop(sprintf("%s '%s' does not exist", name, path))
  }
}


is_directory <- function(path) {
  file.info(path)$isdir
}


set_names <- function(x, nms) {
  names(x) <- nms
  x
}


## NOTE: This does not return if the *compiler* supports openmp, just
## the runtime.  While we are testing that will be the same thing, but
## after installation from binary this requires really a compile time
## test of a simple openmp program.
openmp_info <- function() {
  env <- Sys.getenv(c("OMP_THREAD_LIMIT", "OMP_NUM_THREADS"))
  env <- set_names(as.list(as.integer(env)), names(env))
  info <- cpp_openmp_info()
  c(info, env)
}


vcapply <- function(x, fun, ...) {
  vapply(x, fun, character(1), ...)
}


is_call <- function(x, name) {
  is.call(x) && identical(deparse(x[[1]]), name)
}


dust_header <- function(comment) {
  sprintf("%s Generated by dust (version %s) - do not edit",
          comment, packageVersion("dust"))
}
