on:
  push:
    branches:
      - master
      - main
      - mrc-3377

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: pkgdown
          needs: website

      - name: Install package
        run: R CMD INSTALL .

      - name: Install sphinx/doxygen dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends doxygen
          sudo pip3 install --upgrade Sphinx breathe furo pygments

      - name: Build site
        run: ./scripts/docs_build

      - name: Deploy site
        run: ./scripts/docs_push
